# Generated by Django 5.0.1 on 2024-01-31 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_evento_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='asistentes', to=settings.AUTH_USER_MODEL),
        ),
    ]
